# Generated by Django 3.2.16 on 2025-02-03 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0077_auto_20250129_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='userStatistics_snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('newAccounts', models.IntegerField(default=0)),
                ('nValidations_submitted', models.IntegerField(default=0)),
            ],
        ),
    ]
