# Generated by Django 3.2.16 on 2025-02-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0078_userstatistics_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics_snapshot',
            name='deactivatedAccounts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics_snapshot',
            name='nFiles_uploaded',
            field=models.IntegerField(default=0),
        ),
    ]
