# Generated by Django 3.2.16 on 2025-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0079_auto_20250203_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics_snapshot',
            name='nSuccessfulValidations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics_snapshot',
            name='nUniqueUsers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics_snapshot',
            name='total_uploadSize',
            field=models.FloatField(default=0),
        ),
    ]
