# Generated by Django 3.2.16 on 2025-02-03 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0080_auto_20250203_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('newAccounts', models.IntegerField(default=0)),
                ('deactivatedAccounts', models.IntegerField(default=0)),
                ('nFiles_uploaded', models.IntegerField(default=0)),
                ('total_uploadSize', models.FloatField(default=0)),
                ('nValidations_submitted', models.IntegerField(default=0)),
                ('nSuccessfulValidations', models.IntegerField(default=0)),
                ('nUniqueUsers', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='userStatistics_snapshot',
        ),
        migrations.AddField(
            model_name='validationrun',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('SCHEDULED', 'Scheduled'), ('ERROR', 'Error'), ('RUNNING', 'Running'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10),
        ),
    ]
