# Generated by Django 3.2.16 on 2025-02-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0082_dataset_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
