# Generated by Django 3.2.16 on 2025-02-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0083_datasetversion_usage_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='snapshot',
        ),
        migrations.AddField(
            model_name='user',
            name='expiry_notified',
            field=models.BooleanField(default=False),
        ),
    ]
