# Generated by Django 3.2.16 on 2025-02-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0084_auto_20250206_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isRemoved',
            field=models.BooleanField(default=False),
        ),
    ]
